FROM golang:1.15-nanoserver-1809 as builder
WORKDIR /request-printer
COPY request-printer.go .
RUN go build -ldflags "-s -w"

FROM mcr.microsoft.com/windows/nanoserver:20H2
COPY --from=builder /request-printer/request-printer.exe /bin/
USER ContainerAdministrator
RUN setx /M path "%path%C:\bin;"
USER ContainerUser
EXPOSE 80
CMD ["request-printer.exe"]