FROM golang:1.20-nanoserver as builder
WORKDIR /request-printer
COPY request-printer.go go.mod ./
RUN go build -ldflags "-s -w"

FROM mcr.microsoft.com/windows/nanoserver:ltsc2022
COPY --from=builder /request-printer/request-printer.exe /bin/
USER ContainerAdministrator
RUN setx /M path "%path%C:\bin;"
USER ContainerUser
EXPOSE 80
CMD ["request-printer.exe"]